export const SPEECH_CONFIG = {
  TOKEN_TTL_SECONDS: 30,

  PER_USER_RATE_LIMIT: 3,
  PER_USER_RATE_WINDOW_SECONDS: 60,

  DAILY_TOKEN_QUOTA: 30,

  ACCOUNT_AGE_HOURS_REQUIRED: 24,
  DEEPGRAM_GRANT_TIMEOUT_MS: 3000,
} as const;
