export const SPEECH_CONFIG = {
  TOKEN_TTL_SECONDS: 600,

  PER_USER_RATE_LIMIT: 20,
  PER_USER_RATE_WINDOW_SECONDS: 60,

  DAILY_TOKEN_QUOTA: 200,

  ACCOUNT_AGE_HOURS_REQUIRED: 24,
  DEEPGRAM_GRANT_TIMEOUT_MS: 3000,
} as const;
